language: go

sudo: false

go:
  - 1.7
  - tip

env:
  GO_ENV: test

install:
  - go get github.com/Masterminds/glide/...
  - go install github.com/Masterminds/glide/...
  - go install ./vendor/github.com/gobuffalo/buffalo/buffalo
  - glide i

script: buffalo test

addons:
  postgresql: "9.3"

matrix:
  allow_failures:
    - go: 'tip'
