development:
  dialect: postgres
  database: gobuffalo_development
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

test:
  dialect: postgres
  database: gobuffalo_test
  user: postgres
  password: postgres
  host: 127.0.0.1

production:
  url: {{env "DATABASE_URL"}}
