
[[dependencies]]
  branch = "development"
  name = "github.com/gobuffalo/buffalo"

[[dependencies]]
  branch = "master"
  name = "github.com/gobuffalo/envy"

[[dependencies]]
  branch = "master"
  name = "github.com/gobuffalo/packr"

[[dependencies]]
  branch = "master"
  name = "github.com/gobuffalo/plush"

[[dependencies]]
  branch = "master"
  name = "github.com/gobuffalo/tags"

[[dependencies]]
  branch = "master"
  name = "github.com/markbates/grift"

[[dependencies]]
  branch = "master"
  name = "github.com/markbates/inflect"

[[dependencies]]
  branch = "master"
  name = "github.com/markbates/willie"

[[dependencies]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

[[dependencies]]
  branch = "master"
  name = "github.com/pkg/errors"

[[dependencies]]
  branch = "master"
  name = "github.com/stretchr/testify"
